Release 6.1.0
ktsstudio/mediaproject-utils pull request #25
Opened 2024-06-06 11:47 UTC by ADdinathe

2025-07-30 13:58 UTC, natalya-z requested changes

2025-07-30 13:58 UTC, natalya-z commented on src/hooks/usePreventDefaultTouchMove.tsx
> +      container.removeEventListener('touchmove', preventDefaultTouchMove);
в removeEventListener надо повторить те же параметры, что и в addEventListener. параметры лучше вынести в объект-переменную

2025-07-30 13:58 UTC, natalya-z commented on src/__tests__/utils/random.ts
> +    return Math.floor(Math.random() * (min - max + 1)) + max;
Как-то путает, что min становится max. Нельзя ли сделать примерно так (код перепроверить):

```
if (min > max) {
        [min, max] = [max, min];
    }
return Math.floor(Math.random() * (max - min + 1)) + min;
```

2025-07-30 13:58 UTC, natalya-z commented on src/__tests__/utils/range.ts
> +  }
как будто бы линтер не прогонялся, тут какие-то пробелы

2025-07-30 13:58 UTC, natalya-z commented on src/__tests__/utils/range.ts
> +    return Array.from({length: (end - start)}, (_, i) => start + i);
массив получается по длине короче на 1, то есть чисто из end никогда не будет попадать в массив, например range(3, 7); 7-3 = 4 элемента, массив из 4 элементов: [3, 4, 5, 6]. 7 не включено. Надо либо поправить код, либо описание, зависит от того, как в lodash сделано, так как функция является аналогом

2025-08-05 09:43 UTC, ADdinathe commented on src/__tests__/utils/range.ts
> +    return Array.from({length: (end - start)}, (_, i) => start + i);
Посмотрел оригинальную функцию. Там не включается конечное число [start, end). Добавил в описание функции

2025-08-05 09:43 UTC, ADdinathe commented on src/__tests__/utils/range.ts
> +  }
прогнал еще раз

2025-08-05 09:44 UTC, ADdinathe commented on src/__tests__/utils/random.ts
> +    return Math.floor(Math.random() * (min - max + 1)) + max;
Переписал на более понятный вид

2025-08-05 09:48 UTC, natalya-z approved these changes

2025-08-06 10:18 UTC, merged