Hooks
ktsstudio/mediaproject-utils pull request #3
Opened 2021-11-02 08:54 UTC by AliceSitedge

2021-11-02 09:33 UTC, natalya-z commented on src/hooks/useOrientationChange.ts
> +const getIsLandscape = () => window.innerWidth > window.innerHeight;
возвращаемый тип забыла

2021-11-11 09:19 UTC, n-merkulova approved these changes

2021-11-11 09:19 UTC, wayvy approved these changes

2021-11-11 09:26 UTC, natalya-z requested changes

2021-11-11 09:26 UTC, natalya-z commented on README.md
> +* [fixActive](./src/fixActive.ts) - утилита для отключения :active
для ios и safari

2021-11-11 09:44 UTC, AliceSitedge commented on src/hooks/useScrollTop.ts
> + * @param {Array<any>} dependencies
Можно еще передавать условие, по которому нужно скроллить наверх, и поставить по умолчанию true. Не всегда это нужно делать при каждом изменении зависимостей

2021-11-11 10:00 UTC, natalya-z approved these changes

2021-11-11 10:15 UTC, merged