Refactor
ktsstudio/mediaproject-utils pull request #5
Opened 2021-12-22 10:17 UTC by AliceSitedge

2021-12-23 09:00 UTC, natalya-z approved these changes

2021-12-23 09:00 UTC, natalya-z commented on src/types/window.ts
> +  is_dev: boolean;
если тут появилось is_dev, в create-mediaproject надо будет не забыть обновить библиотеку и убрать is_dev из Window

2021-12-23 12:34 UTC, n-merkulova approved these changes

2021-12-23 12:34 UTC, n-merkulova commented on src/initializeAppParams.ts
> +  try {
возможно лучше вынести в отдельную функцию/утилиту, вдруг это понадобится проверять не только здесь

2021-12-27 13:53 UTC, n-merkulova commented on src/api.ts
> +    url: urlConfig.url,
мб просто ...urlConfig?

2021-12-27 13:55 UTC, n-merkulova commented on src/api.ts
> +  urlConfig: UrlConfigType,
ну вообще это можно было бы не менять, как мне кажется, и мы могли бы передавать просто с деструктуризацией урл и метод, а то объект внутри объекта выходит немного громоздко будто бы

2021-12-27 13:57 UTC, n-merkulova commented on src/checkDev.ts
> +    const domains = location.host.split('.');
а hostname тут не подошел бы? а то в хосте еще порт вроде

2021-12-27 13:59 UTC, n-merkulova requested changes

2021-12-27 13:59 UTC, n-merkulova commented on src/checkDev.ts
> +      domain?.includes('ktsdev') ||
ktsdev лучше вынести в аргументы функции и сделать ему значение по умолчанию 'ktsdev'

2021-12-27 13:59 UTC, n-merkulova commented on src/checkDev.ts
> +export default function checkDev(isProduction: boolean): boolean {
мб лучше внутри читать из window? или тут сделать значение по умолчанию = window.is_production

2022-01-17 12:53 UTC, n-merkulova approved these changes

2022-01-17 12:54 UTC, merged